# Generated by Django 2.0.2 on 2020-06-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blogTitle', models.CharField(max_length=300)),
                ('blogImage', models.ImageField(upload_to='images/')),
                ('blogDescription', models.TextField()),
                ('blogBody', models.TextField()),
                ('uplaodBy', models.CharField(max_length=30)),
                ('publishDate', models.DateTimeField()),
            ],
        ),
    ]
